#BASE DE DATOS

CREATE DATABASE Users;

USE Users;
CREATE TABLE Registered_users (
	Id INT NOT NULL AUTO_INCREMENT,
    User VARCHAR(25) NOT NULL,
    Name VARCHAR(25) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Password VARCHAR(25) NOT NULL,
    PRIMARY KEY (Id)
);